"""Concept-first blocks: (key idea, mental model, when NOT to use it) for every lesson."""

CONCEPTS = {
    "L01": ("A workflow is a pipeline of nodes; each node receives a **list of items** (JSON objects) and returns a list of items.",
            "An assembly line: each station (node) takes the trays (items) coming in, does one job, and passes trays on.",
            "This lesson uses a Code node so you can see items directly. In real workflows, prefer Set, IF and Filter when they can do the job: visual nodes are easier for the next person to read."),
    "L02": ("Triggers decide **when** a workflow runs; a Config node decides **with what settings**.",
            "An alarm clock (Schedule) wakes a worker who first reads the sticky note on the fridge (Config) before starting the day.",
            "Don't schedule every minute \"just in case\". Choose the slowest schedule the business can live with, since APIs rate-limit and executions cost money."),
    "L03": ("Every API is just a URL + method + auth + parameters; the hard part is **reading the JSON it returns**.",
            "Ordering from a restaurant menu: the endpoint is the dish, the query parameters are your customisations, the credential is your membership card.",
            "Don't scrape a site when it has an official API. APIs are stable, legal and structured."),
    "L04": ("Branching sends items down different paths based on rules; **IF** has two roads, **Switch** has many, and there's always a road for \"none of the above\".",
            "Railway points: each train (item) is switched onto a track by a rule, and a siding (fallback) catches the rest.",
            "Don't nest five IFs. When you have three or more outcomes, one Switch with named outputs is clearer."),
    "L05": ("The Code node is for **reshaping many items at once**: filter, dedupe, sort, group, and many→one.",
            "A spreadsheet formula column plus a pivot table, written in a few lines of JavaScript.",
            "Don't hide business rules in 80 lines of code. If a non-developer must change it, use Set/IF/Switch or a Config node."),
    "L06": ("Files travel as **binary data** next to the JSON; and every polling workflow must mark what it has processed (**idempotency**).",
            "A parcel (binary) with a delivery note (JSON) attached. The postman must stamp \"delivered\" or he'll deliver it again tomorrow.",
            "Don't poll every minute for things that can push events to you (webhooks). Polling costs API quota."),
    "L07": ("A form + a sheet is the simplest possible **system of record**: capture, clean, store, acknowledge.",
            "A reception desk: take the visitor's details, write them neatly in the register, hand them a receipt.",
            "Don't use Sheets as a database beyond a few thousand rows or with several writers at once. Move to Airtable, Postgres or a CRM."),
    "L08": ("Query the tool of record (**JQL**) instead of copying data; send a digest only when it's useful.",
            "A morning newspaper printed only with today's stuck stories, delivered before stand-up.",
            "Don't email the whole team a list they will ignore. Target the owner, or post where the team already talks."),
    "L09": ("A webhook turns a workflow into **your own API**: validate input, authenticate the caller, return honest status codes.",
            "A shop counter with a guard (auth), a checker (validation) and a receipt printer (201 / 400).",
            "Don't expose a webhook without authentication, and don't do slow work before responding if the caller has a timeout. Respond first, then process."),
    "L10": ("Translate the **user's language** into the **system's language** at the boundary (Severity → Priority).",
            "An interpreter at the front desk: the customer says \"it's broken\", the ticket says \"Highest, Auth module\".",
            "Don't let free-text forms create tickets without structure. Required fields and dropdowns save hours of triage."),
    "L11": ("An LLM chain is a **function**: prompt + data in, text out. Control it with a clear system prompt and a low temperature.",
            "A very fast intern: great at summarising, needs precise instructions, and should never be trusted with facts it wasn't given.",
            "Don't use an LLM for things code does exactly (sums, dates, filters). It's slower, costs money and can be wrong."),
    "L12": ("**Structured output** turns messy text into rows your workflow can branch on and store.",
            "A form the AI must fill in: fixed boxes (schema) instead of a blank page.",
            "Don't ask for JSON only in the prompt. Use an output parser, so malformed answers are caught and retried."),
    "L13": ("**RAG** answers from *your* documents: chunk → embed → store → retrieve → answer with sources.",
            "An open-book exam: the model may answer only from the pages it was handed, and must say which page.",
            "Don't use RAG when the answer is in one short document. Just paste it into the prompt. RAG earns its keep with large or changing document sets."),
    "L14": ("An **agent** decides which tools to call and in what order; tool descriptions are the agent's user manual.",
            "A capable assistant with a phone (HTTP), a calculator and an encyclopedia, who chooses which to use for each question.",
            "Don't use an agent for a fixed sequence of steps. A normal workflow is faster, cheaper and predictable."),
    "L15": ("**Human-in-the-loop**: the AI proposes, a person approves, and the execution pauses until they decide.",
            "A junior drafts, the manager signs. Nothing leaves the building without a signature.",
            "Don't add approvals to low-risk, high-volume steps. You'll create a bottleneck and people will approve blindly."),
    "L16": ("**Sequential specialists**: several narrow agents, each building on the previous one's output, plus a coordinator.",
            "A newsroom: a reporter per beat, and an editor who writes the front page from their notes.",
            "Don't split into many agents when one good prompt works. Each agent adds cost, latency and another place to be wrong."),
    "L17": ("Every agent step returns **validated JSON**, and a fix-model repairs malformed output automatically.",
            "A factory line with an inspector after every station, sending faulty parts back for rework.",
            "Don't auto-send AI-written customer emails until you've measured accuracy. Add L15's approval step first."),
    "L18": ("Document AI = **extract text first**, then let specialists analyse; the quality of step 1 limits everything after it.",
            "Photocopy the CV, then hand copies to four reviewers with different checklists.",
            "Don't feed scanned images to a text extractor. Add OCR, or the AI analyses an empty page."),
    "L19": ("One **error workflow** watches all others; failures become alerts with a human-readable hint.",
            "A smoke detector wired to every room, calling you with \"kitchen, probably toast\".",
            "Don't alert on every retryable blip. Use Retry on Fail first, and alert when retries are exhausted."),
    "L20": ("**Sub-workflows are functions**: typed inputs, one job, a return value, reused everywhere.",
            "A company stamp: design it once, every department uses the same one.",
            "Don't extract a sub-workflow used only once. Premature reuse makes debugging harder."),
    "L21": ("**Alert on change, not on state**: remember the last state between runs and only speak when it changes.",
            "A doorbell that rings when someone arrives, not every five minutes while they stand there.",
            "Don't rely on static data for critical state in multi-instance setups. Use a database table."),
    "L22": ("Combine it all: **form → AI decision with reasons → route → store → act**.",
            "A receptionist who reads each enquiry, scores it, files it, and calls sales for the hot ones.",
            "Don't let the score be a black box. Store the `reason` next to the score, so humans can audit and tune."),
    "Q01": ("Use **Luxon dates** (`$today`, `.plus()`) and simple algorithms to turn raw calendar data into a decision (where's my focus time?).",
            "A personal assistant who reads your diary and says \"your best hour is 11–12\".",
            "Don't read the whole calendar. Always pass a time window."),
    "Q02": ("**Scrape → extract → remember → compare**; alert on thresholds and on relative change.",
            "A friend who checks the shop window every six hours and texts you only when the price drops.",
            "Don't scrape sites that forbid it or render prices with JavaScript. Use their API or a feed."),
    "Q03": ("A chat bot is just **trigger → parse → act → reply**, and chat is the easiest UI you'll ever build.",
            "Texting a very organised friend who files everything you send them.",
            "Don't leave a bot open to everyone. Check the sender's ID before acting."),
    "Q04": ("Surface **stuck work** where the team already is, with names, so it gets unblocked.",
            "A polite colleague who walks the floor at 10 AM asking \"who's waiting on a review?\".",
            "Don't nudge on drafts or weekends. Filter the noise, or people mute the channel."),
    "Q05": ("**Aggregate → chart → email**: a picture of the trend beats a table of numbers.",
            "A one-slide Monday briefing, printed and on your desk.",
            "Don't chart vanity metrics. Pick the one number the team can act on."),
    "Q06": ("**State in the sheet** (`last_reminded`) makes a scheduled job safe to run again and again.",
            "A ledger where you tick \"reminded today\", so you never call a client twice in one day.",
            "Don't compute \"today\" with `new Date()` (UTC). Use `$today`, which respects the workflow timezone."),
    "Q07": ("The **Text Classifier** routes each item to one output per category; category descriptions are the prompt.",
            "A mail-room clerk sorting envelopes into pigeonholes by reading the first few lines.",
            "Don't let a classifier *act* (reply, delete) at first. Label only, then measure accuracy."),
    "Q08": ("**Deduplicate across executions** so each item is processed once, ever, even after restarts.",
            "A bouncer with a guest list who remembers everyone already let in.",
            "Don't dedupe on a field that changes (titles get edited). Use a stable ID or URL."),
    "Q09": ("A **webhook turns any external event into an n8n trigger**; shape the payload into flat fields before you use them.",
            "A doorbell: someone else presses it (Jira), you just react.",
            "Never leave a webhook unauthenticated. Anyone who finds the URL can post fake events."),
    "P01": ("**AI extracts, code validates, humans approve above a threshold**; bad inputs go to an exceptions queue.",
            "A junior clerk types the invoice, a calculator re-checks the maths, the manager signs the big ones.",
            "Don't let the model's arithmetic or guesses reach your ledger unchecked, and don't auto-approve without a limit."),
    "P02": ("The **copilot pattern**: AI prepares a grounded draft with a confidence score; a human sends it.",
            "An assistant who drafts replies from the company FAQ and leaves them in your outbox, never pressing send.",
            "Don't auto-send until you have weeks of accuracy data on a narrow category."),
    "P03": ("Turn an **alert storm into one incident**: dedupe by fingerprint, route by severity, close the loop on resolve.",
            "A hospital triage nurse: one patient file per person, no matter how many times the alarm beeps.",
            "Don't page humans for warnings. Only critical alerts should wake someone up."),
    "P04": ("**Long-running executions**: Wait nodes pause one lead's journey for days; stop as soon as they reply.",
            "A patient salesperson with a follow-up diary who crosses a name off the moment the customer calls back.",
            "Don't run multi-day waits on a laptop or SQLite. Use an always-on server with Postgres."),
    "P05": ("Process big lists with **batches + checkpoints + rate limits**, so any run can stop and resume safely.",
            "Marking exam papers in piles of ten, ticking each one, so a fire drill doesn't make you start over.",
            "Don't read the summary from `$('node').all()` inside loops (it's the last batch only). Use the loop's done output."),
    "P06": ("**Routing rules + timeouts + audit trail** make approvals trustworthy without an approvals product.",
            "A relay race: the baton (request) passes manager → finance, with a referee (timeout) and a scoreboard (audit sheet).",
            "Don't model every exception as a new branch. Keep rules few and visible in the Config node."),
    "P07": ("**Fan-out / fan-in**: one trigger starts parallel branches; Merge waits for all of them before the summary.",
            "A wedding planner who calls caterer, florist and venue in parallel, then confirms with the couple once all say yes.",
            "Don't Merge branches that may produce 0 items. Aggregate first, so each branch returns exactly one item."),
    "P08": ("**Idempotent one-way sync**: create when there's no key, update when the hash changed, otherwise skip, and write the key back.",
            "A librarian who stamps each book with a catalogue number and only re-files books whose cover changed.",
            "Don't start with two-way sync. Conflicts (both sides edited) need rules you must design first."),
    "P09": ("A research agent should **plan → search → read → cross-check → cite**, and say \"not found\" instead of guessing.",
            "A junior analyst who shows their sources in footnotes.",
            "Don't treat the report as final. It's a first draft that saves 80% of the time, and a human checks key facts."),
    "P10": ("**MCP** lets AI assistants call your workflows as tools: authenticated, logged, and governed by you.",
            "A staff-only door with a keycard reader: assistants can come in, but only to the rooms you allow.",
            "Don't expose write actions (refunds, deletes) as MCP tools without an approval step."),
    "P11": ("An **AI gateway** minimises data: redact PII before the model sees it, block obvious abuse, log without raw PII.",
            "Posting a letter with the address blacked out. The courier (model) can still deliver the message, but can't read who it's for.",
            "Don't rely on keyword injection filters alone. They're a first layer, not a security boundary."),
    "P12": ("**Numbers from code, narrative from AI**: join systems in parallel, compute deltas, then explain them.",
            "An analyst builds the table; a chief of staff writes the three bullets the CEO actually reads.",
            "Don't let the model compute or \"estimate\" KPIs. It only narrates numbers it's given."),
}
