"""Practice challenges per lesson: (stars, challenge, hint, solution-markdown)."""

EX = {
    "X01": [
        (1, "**Bug 1:** only some orders (or none) get through *Paid Only*.",
         "Open *Orders* and *Paid Only* side by side. Compare the status value in the data with the value in the condition, character by character.",
         "The data says `Paid`, the filter compares with `paid`, and Filter is case-sensitive by default. Either type `Paid`, or open the Filter's **Options → Ignore Case**. Ignoring case is safer when data comes from people."),
        (1, "**Bug 2:** `total` is empty.",
         "Open *Add Tax* and look at the expression preview under the field. Then look at the INPUT panel: which field names actually exist?",
         "The expression says `$json.ammount` (two m's). A missing field is `undefined`, and `undefined * 118` is `NaN`, so n8n leaves it empty without an error. Fix it to `{{ Math.round($json.amount * 118) / 100 }}`. Drag fields from the INPUT panel instead of typing them to avoid this."),
        (2, "**Bug 3:** every order has the same label.",
         "Check the Code node's mode. In *Run once for all items*, what does `$json` point to?",
         "In *Run once for all items* mode, `$json` is the **first** item only. Inside the `map`, use the loop variable:\n```javascript\nreturn $input.all().map(i => ({ json: { ...i.json, label: `#${i.json.order_id} · ${i.json.customer}` } }));\n```\nOr switch the node to *Run once for each item*, where `$json` is the current item."),
    ],
    "X02": [
        (1, "**Bug 1:** *Join on Company* outputs nothing.",
         "Open the Merge node's two INPUT tabs. The field you match on must exist, spelled the same, in both.",
         "Leads use `company`, Companies use `Company`. Keys are case-sensitive, so nothing matches. In the Merge node, turn on **Fields to match have different names** and set Input 1 field `company`, Input 2 field `Company`. (Or rename the field with a Set node before the merge.)"),
        (2, "**Bug 2:** Pixel Studio (9 employees) ranks above Kiranmart (1,200).",
         "Look at `size` in the OUTPUT panel of *Size*. Is it shown as a number or as text?",
         "The Set field's type is **String**, so Sort compares text, and `\"9\"` comes after `\"1200\"`. Change the field type to **Number**."),
        (2, "**Bug 3:** sorting is right, but the top 2 are still wrong.",
         "What does *Top 2* receive, and what does *Biggest First* receive? Follow the connections, not the node names.",
         "*Top 2* runs **before** *Biggest First*, so it keeps the first 2 items in the original order and only then sorts them. Rewire it as `Size → Biggest First → Top 2 → ✅ Check`."),
    ],
    "L01": [
        (1, "Send the greeting for **three people** instead of one.",
         "The Set node emits one item. What if the Code node returned three?",
         "In **Build Greeting**, replace the code with:\n```javascript\nconst people = [['Asha', 'Chennai'], ['Ravi', 'Pune'], ['Meera', 'Delhi']];\nreturn people.map(([name, city]) => ({ json: { name, city, greeting: `Hello ${name} from ${city}!` } }));\n```\nGmail now runs **three times**, once per item. That's the core n8n idea: nodes run once per item."),
        (2, "Put all three greetings into **one** email instead of three.",
         "You need *many → one*. Either a Code node in *Run once for all items* mode, or the **Aggregate** node.",
         "Add an **Aggregate** node after Build Greeting: *Individual fields* → field `greeting`. In Gmail, set Message to `{{ $json.greeting.join('<br>') }}`. One item goes in, so one email goes out."),
    ],
    "L02": [
        (1, "Send the email only when it's likely to rain (> 50%).",
         "Add a node between *Fetch Weather* and *Email Summary* that can stop items.",
         "Add an **IF** (or **Filter**) node: `{{ $json.daily.precipitation_probability_max[0] }}` *is greater than* `50`. Connect only the **true** output to Gmail."),
        (2, "Report the weather for **3 cities** in one email.",
         "Make Config emit 3 items (Code node), let HTTP run per item, then combine.",
         "Replace ⚙️ Config with a Code node returning 3 items `{city, latitude, longitude, timezone}`. HTTP Request runs once per city automatically. Add a Code node (*all items*) that builds one HTML table:\n```javascript\nconst cfg = $('⚙️ Config').all();\nconst rows = $input.all().map((it, i) => `<tr><td>${cfg[i].json.city}</td><td>${it.json.daily.temperature_2m_max[0]}°C</td><td>${it.json.daily.precipitation_probability_max[0]}%</td></tr>`).join('');\nreturn [{ json: { html: `<table>${rows}</table>` } }];\n```"),
    ],
    "L03": [
        (1, "Only include jobs posted **today** or **\"hours ago\"**.",
         "Look at `detected_extensions.posted_at` in the API output.",
         "In *Format Email*, filter before slicing:\n```javascript\nconst jobs = ($input.first().json.jobs_results || [])\n  .filter(j => /hour|today|just/i.test(j.detected_extensions?.posted_at || ''))\n  .slice(0, cfg.max_jobs);\n```"),
        (2, "Never email the same job twice across days.",
         "n8n can remember items between runs, with no database needed.",
         "Before *Format Email*, add a Code node that splits `jobs_results` into items (`return $json.jobs_results.map(j => ({ json: j }))`), then **Remove Duplicates** → *Remove items processed in previous executions* on `{{ $json.job_id }}`. Adjust Format Email to read `$input.all()` instead of `jobs_results`. This is the Q08 pattern."),
    ],
    "L04": [
        (1, "Add a third zone: **Watch** when the rate is within 0.5 of either threshold.",
         "Switch rules are evaluated in order; the first match wins (unless *Send data to all matching outputs* is on).",
         "Add a rule *before* the fallback: `{{ Math.min(Math.abs($json.rate - $('⚙️ Config').item.json.high), Math.abs($json.rate - $('⚙️ Config').item.json.low)) }}` *is less than* `0.5`, renamed `Watch`, connected to a gentle email."),
        (2, "Stop the hourly spam: alert at most **once per day per zone**.",
         "Remember when you last alerted with `$getWorkflowStaticData`.",
         "Before each alert, add a Code node:\n```javascript\nconst s = $getWorkflowStaticData('global');\nconst key = 'High:' + $today.toISODate();\nif (s[key]) return [];      // already alerted today → drop the item\ns[key] = true;\nreturn $input.all();\n```\nStatic data only persists in **active** executions (see L21)."),
    ],
    "L05": [
        (1, "Add Hacker News (`https://hnrss.org/frontpage`) as a 4th source.",
         "Merge has a *Number of inputs* setting.",
         "Add an RSS Read node with the URL (On Error → Continue), set Merge *Number of inputs* to 4, and wire the new feed to input 4. The Code node needs no change, because it reads `$input.all()`."),
        (2, "Group the digest by **source** with a heading per site.",
         "Use `reduce` to build `{ source: [articles] }`, then render.",
         "At the end of the Code node, replace the `li` line:\n```javascript\nconst groups = articles.reduce((g, a) => ((g[a.source] ??= []).push(a), g), {});\nconst html = Object.entries(groups).map(([src, list]) => `<h3>${src}</h3><ol>${list.map(a => `<li><a href=\"${a.link}\">${a.title}</a></li>`).join('')}</ol>`).join('');\n```\nand return `html` instead of `<ol>${li}</ol>`."),
    ],
    "L06": [
        (1, "Save PDFs into a sub-folder **per sender domain** (e.g. `/airtel.com`).",
         "You can build the file name, or use a Drive *Create folder* step first.",
         "Quick version: prefix the name. In *Split PDF Attachments*, add `const domain = (item.json.from?.text || '').split('@')[1]?.replace('>', '') || 'unknown';` and use `` fileName: `${domain}/${date}_${name}` ``. Proper version: *Drive → Search folder by name*, create it if missing (IF), then upload into its ID."),
        (2, "Skip files you already saved, even if the same PDF arrives in a new email.",
         "Hash the file content; the Crypto node can hash binary data.",
         "After the split, add **Crypto → Hash → SHA256** with *Binary file* on (property `data`), output `sha`. Then **Remove Duplicates → previous executions** on `{{ $json.sha }}`. Same bytes, same hash, so the file is skipped."),
    ],
    "L07": [
        (1, "Reject personal email domains (gmail, yahoo, hotmail) with a polite message.",
         "Add an IF after *Clean Lead*.",
         "IF `{{ /@(gmail|yahoo|hotmail|outlook)\\./i.test($json.email) }}` *is true*: send a \"please use your work email\" reply and stop. On false, continue to Sheets."),
        (2, "Don't store duplicate leads. Update the existing row instead.",
         "Sheets has an *Append or Update* operation with a matching column.",
         "Change the Sheets operation to **Append or Update Row**, matching column `email`. Resubmitting the form now updates the same row (like Q06 and P04)."),
    ],
    "L08": [
        (1, "Only include **High/Highest** priority stale stories.",
         "Fix it in JQL, not in code, so Jira does the filtering.",
         "Append to the JQL: `AND priority in (High, Highest)`. Filtering at the source means less data, faster runs and an easier workflow."),
        (2, "DM each assignee their own list instead of one team email.",
         "Group by assignee, then one item per person → Slack/email node runs per item.",
         "Replace the report Code with:\n```javascript\nconst by = {};\nfor (const i of $input.all().map(x => x.json).filter(j => j.key)) {\n  const who = i.fields.assignee?.emailAddress || 'unassigned@example.com';\n  (by[who] ??= []).push(`${i.key} ${i.fields.summary}`);\n}\nreturn Object.entries(by).map(([email, list]) => ({ json: { email, text: list.join('\\n') } }));\n```\nSend to `{{ $json.email }}`."),
    ],
    "L09": [
        (1, "Add an optional `date` field that must be a real date **not in the future**.",
         "Luxon: `DateTime.fromISO(x).isValid`.",
         "In *Validate*:\n```javascript\nif (b.date) {\n  const d = DateTime.fromISO(b.date);\n  if (!d.isValid) errors.push('date must be YYYY-MM-DD');\n  else if (d > $now) errors.push('date cannot be in the future');\n}\n```"),
        (2, "Return **200 with the existing row** if the same expense is posted twice within a minute (idempotency).",
         "Clients retry on timeouts. Accept an `Idempotency-Key` header and remember recent keys.",
         "In *Validate*, read `$json.headers['idempotency-key']`, keep recent keys in `$getWorkflowStaticData('global').keys` (key → row, with a timestamp), and if it was seen less than 60 s ago, route to a *Respond 200* with the saved row instead of appending. This is how payment APIs (Stripe) avoid double charges."),
    ],
    "L10": [
        (1, "Add a **Screenshot** file field and attach it to the Jira issue.",
         "The Form Trigger has a *File* field type; the Jira node can add attachments.",
         "Add a form field *File* named `Screenshot`. After *Create Jira Bug*, add **Jira → Issue Attachment → Add** with issue key `{{ $json.key }}` and binary property `Screenshot`."),
        (2, "Detect probable duplicates before creating a new bug.",
         "Search Jira for open bugs with similar words first.",
         "Before creating the bug, run **Jira → Get many** with JQL `project = X AND statusCategory != Done AND text ~ \"{{ $json['What is broken?'] }}\"`. IF there are results, comment on the top one instead of creating a new issue, and tell the reporter the existing key."),
    ],
    "L11": [
        (1, "Make the briefing **5 bullets max, in simple English for a school student**.",
         "Change only the system message; keep the data the same.",
         "Edit the system message: *\"…write for a 14-year-old. Max 5 bullets, max 20 words each. No jargon.\"* Compare outputs. Prompts are code: version them."),
        (2, "Return **JSON** and render your own HTML template (no HTML from the model).",
         "Turn on *Require specific output format* and attach a Structured Output Parser.",
         "Parser example: `{\"stories\":[{\"title\":\"\",\"why_it_matters\":\"\",\"link\":\"\"}],\"trend\":\"\"}`. Then a Code node renders the HTML. The model can no longer break your layout."),
    ],
    "L12": [
        (1, "Add a `due_date` field (YYYY-MM-DD or empty) to each RAID item.",
         "Update the parser example and the *Build RAID Row* Set node.",
         "Add `\"due_date\": \"2026-10-15\"` to the example items, add a `due_date` column to the sheet and a `due_date = {{ $json.due_date }}` field in the Set node."),
        (2, "Email the **owner** of every high-impact Risk right after logging it.",
         "Filter the split items, then email per item.",
         "After *Split RAID Items*, branch a **Filter**: `category = Risk` AND `impact` contains `high` (or add an `impact_level` enum to the schema). Then Gmail per item. Owners need emails, so map names → emails with a small Code lookup table."),
    ],
    "L13": [
        (1, "Make the bot cite the **policy section number** in every answer.",
         "It's a prompt change plus good chunking.",
         "System message: *\"End every answer with 'Source: <document> §<section>'.\"* Keep sections intact by making chunks slightly larger (e.g. 1500 characters) so a section isn't split."),
        (2, "Move from in-memory to a **persistent** vector store.",
         "Swap both vector store nodes; embeddings stay the same.",
         "Replace both In-Memory Vector Store nodes with **Supabase** / **Qdrant** / **PGVector** (same insert and retrieve-as-tool modes, same embeddings). Documents now survive restarts, and several workflows can share the knowledge base."),
    ],
    "L14": [
        (1, "Add a **time-in-city** tool.",
         "Another HTTP Request Tool with a placeholder.",
         "HTTP Request Tool `get_time`: URL `https://timeapi.io/api/Time/current/zone?timeZone={tz}`, placeholder `tz` (\"IANA timezone like Asia/Kolkata\"). Ask: *\"What time is it in Tokyo?\"*"),
        (2, "Cap the cost: refuse questions unrelated to weather, currency, maths or general knowledge.",
         "Guard **before** the agent runs.",
         "Add a **Text Classifier** before the agent (categories: supported / unsupported). Route unsupported to a fixed reply. Cheap guards in front of expensive agents are a common production pattern."),
    ],
    "L15": [
        (1, "Let the Scrum Master **edit** the action items, not just approve them.",
         "Send and Wait has a *Free text* and a *Custom form* response type.",
         "Change the approval to **Response type: Custom form** with a textarea prefilled with the items. Parse the edited text into items before creating Jira tasks."),
        (2, "Collect retros from the **whole team for a week**, then analyse them together.",
         "Store submissions, then run the analysis on a schedule.",
         "Form → Sheets append (one row per person). A second workflow: Schedule (Friday) → Sheets read this sprint's rows → Aggregate → the same LLM + approval flow. Themes across 8 people are much stronger than 1."),
    ],
    "L16": [
        (1, "Run the three specialist agents **in parallel** instead of in sequence.",
         "Fan out from *Compute Sprint Metrics*, fan in with Merge.",
         "Connect Compute Sprint Metrics to all three agents. Add a **Merge** (3 inputs, combine by position) before the Coordinator, and change the Coordinator prompt to read the three outputs from the merged item. Total time ≈ the slowest agent, not the sum."),
        (2, "Swap GitHub Projects for **Jira** as the data source.",
         "Only the fetch + metrics steps change; agents stay the same.",
         "Replace the GraphQL request with **Jira → Get many** (`sprint in openSprints()`), and adapt *Compute Sprint Metrics* to read `fields.status.statusCategory.key` and your story-points custom field. Keeping the metrics JSON shape the same means no prompt changes."),
    ],
    "L17": [
        (1, "Stop auto-sending: require approval for **escalated** complaints.",
         "Use the escalation agent's `escalate` flag.",
         "Before *Send Response Email*, add an IF on `{{ $('Check Escalation').item.json.output.escalate }}`. On true, send a Gmail **Send and Wait** to the team lead with the draft (L15 pattern); on false, send directly."),
        (2, "Log every complaint with category, urgency and resolution to a sheet for weekly analysis.",
         "All the fields exist in earlier agents' outputs.",
         "Add a Set node pulling `$('Understand Complaint').item.json.output.category`, `.urgency`, `$('Determine Resolution').item.json.output.resolution_workflow`, and the escalation flag, then Sheets append. After a month you'll know your top 3 complaint causes."),
    ],
    "L18": [
        (1, "Add a numeric **fit score** to the email subject.",
         "Ask the Job Fit agent for structured output.",
         "Attach a Structured Output Parser to *Job Fit Analyst* with `{\"score\": 78, \"summary\": \"...\"}`. Subject: `Fit {{ $('Job Fit Analyst').item.json.output.score }}/100: …`."),
        (2, "Rank **20 resumes** against one JD and email a shortlist.",
         "Loop over files; score each; sort; take the top 5.",
         "Upload multiple files (form *Multiple files* on) → split into items → Extract text → the Job Fit agent with a score schema → **Sort** by score desc → **Limit** 5 → one summary email. Don't let AI make hiring decisions alone; this produces a shortlist for a human."),
    ],
    "L19": [
        (1, "Also send the alert to **Slack**.",
         "Add a parallel branch from *Shape Error*.",
         "Add a Slack *Send message* node connected to Shape Error, with *On Error → Continue* so a Slack outage never hides the email."),
        (2, "Send a **weekly error report** grouped by workflow.",
         "Read the Errors sheet on a schedule and aggregate.",
         "New workflow: Schedule (Monday) → Sheets read `Errors` → Code: filter the last 7 days, count by `workflow`, sort desc → email the top 5 with counts and the most common hint. Flaky workflows show up before users complain."),
    ],
    "L20": [
        (1, "Add an optional **CTA button** to birthday emails linking to a team photo album.",
         "L20a already supports `cta_text` and `cta_url`.",
         "In *Who Celebrates Today?*, set `cta_text: 'See team photos'` and `cta_url: 'https://photos.example.com/team'`. No change to L20a. That's the point of sub-workflows."),
        (2, "Make an **L20b** sub-workflow *\"log to audit sheet\"* and call it from L20 and L19.",
         "Execute Workflow Trigger with inputs `workflow`, `event` and `details`.",
         "L20b: Execute Workflow Trigger (workflow, event, details) → Set (time = `$now.toISO()`) → Sheets append `Audit`. Call it with **Execute Workflow** from L20 (event `wish_sent`) and L19 (event `error`). One audit trail for everything."),
    ],
    "L21": [
        (1, "Alert when a site is **slow** (> 3 s) three checks in a row.",
         "Keep a counter per site in static data.",
         "In *Compare with Last State*: `state.sites[url].slow = ms > 3000 ? (state.sites[url].slow || 0) + 1 : 0;` and set `changed = changed || state.sites[url].slow === 3`."),
        (2, "Compute a weekly **uptime %** per site from the Uptime sheet.",
         "Uptime = UP checks / all checks.",
         "Schedule weekly → Sheets read `Uptime` → Code: filter the last 7 days, group by `url`, `pct = up / total * 100` rounded to 2 decimals → email a table sorted by worst first."),
    ],
    "L22": [
        (1, "Add **Budget** as a form field and let it influence the score.",
         "Form field + prompt mention; the schema stays the same.",
         "Add the dropdown *Budget* (< 1L / 1–5L / > 5L), include it in the prompt text, and add to the system message: *\"budget > 5L adds up to 15 points\"*. Re-test the 3 sample leads."),
        (2, "Add a **human approval** before the AI reply is sent to hot leads.",
         "Insert Send-and-Wait between the alert and the personal reply.",
         "Put a Gmail **Send and Wait** (response: free text) to the sales lead, showing the AI draft. Use the edited text if provided (`{{ $json.data.text || $('Build CRM Row').item.json.reply }}`)."),
    ],
}

EX.update({
    "Q01": [
        (1, "Skip meetings you've **declined**.",
         "Each attendee has a `responseStatus`; find yourself with `self: true`.",
         "Extend the filter: `.filter(e => !(e.attendees || []).some(a => a.self && a.responseStatus === 'declined'))`."),
        (2, "Automatically **block** your biggest free slot as \"Focus time\".",
         "Pick the longest slot in code, then create an event.",
         "In Build Agenda also return `best = free.sort((a, b) => (b[1] - b[0]) - (a[1] - a[0]))[0]`. Add **Google Calendar → Create event** with start/end from `best`, summary `🎯 Focus time`, and *Show me as busy*."),
    ],
    "Q02": [
        (1, "Track a product from a site you use (find the CSS selector yourself).",
         "Chrome → right-click the price → Inspect → right-click → Copy selector.",
         "Add `{ name, url, selector, target }` to ⚙️ Products. If `price` comes back `NaN`, the price is rendered by JavaScript. Look for a JSON API in the Network tab instead."),
        (2, "Log every check to a sheet and include a **30-day low** in the alert.",
         "Append each result to Sheets; read the history when alerting.",
         "After *Compare with Last Price*, append `{time, name, price}` to `PriceHistory`. Before the alert, read the history, filter the last 30 days for that product, and compute `Math.min(...)`. Put it in the email: *\"lowest in 30 days: …\"*"),
    ],
    "Q03": [
        (1, "Add a `/today` command that replies with today's total spend.",
         "Read the Inbox sheet, filter today's expenses, sum them.",
         "In Parse Command, add `kind: 'report'` for `/today`. Route it (Switch) to Sheets read → Code `rows.filter(r => r.kind === 'expense' && r.time.startsWith($today.toISODate())).reduce((s, r) => s + Number(r.amount), 0)` → Telegram reply."),
        (2, "Only allow **your own** Telegram account to use the bot.",
         "Every message carries `message.from.id`.",
         "Right after the trigger, add an IF `{{ $json.message.from.id }}` *equals* your ID (send the bot a message once and read it from the execution). Anything else: reply *\"This is a private bot\"* and stop."),
    ],
    "Q04": [
        (1, "Skip weekends and PRs labelled `blocked`.",
         "PR objects have `labels`; Luxon knows the weekday.",
         "Add to the filter: `&& !p.labels.some(l => l.name === 'blocked')`. The cron `0 10 * * 1-5` already skips weekends, but for idle days use business days: count only weekdays between `updated_at` and today."),
        (2, "Check **several repos** and post one combined message.",
         "Config returns N items → HTTP runs per repo → combine.",
         "Make Config a Code node returning one item per repo. HTTP runs per repo; in *Find Stale*, use `$input.all()` and prefix each line with the repo name (`$('⚙️ Config').all()[i].json.repo`)."),
    ],
    "Q05": [
        (1, "Chart **orders** as a second dataset.",
         "QuickChart accepts a data array per dataset, or use a line chart for the second series.",
         "Easiest: a second QuickChart node (line) for orders, output `chart2`, and attach both (`chart`, `chart2`). Advanced: call `https://quickchart.io/chart` via HTTP with a full Chart.js config containing two datasets."),
        (2, "Highlight the week-over-week change in **red/green** in the email body.",
         "Colour based on the sign of `change`.",
         "Message: `<p style=\"color:{{ $json.change >= 0 ? '#16a34a' : '#dc2626' }}\">{{ $json.change >= 0 ? '▲' : '▼' }} {{ $json.change }}%</p>`."),
    ],
    "Q06": [
        (1, "Add a third tone: a **final notice** at 30+ days overdue, cc'd to your accountant.",
         "Extend the stage calculation and the Switch.",
         "In the code: `stage: r.days >= 0 ? 'upcoming' : -r.days >= 30 ? 'final' : 'overdue'`. Add a Switch rule `final` → Gmail with CC (Options → CC)."),
        (2, "Mark invoices **paid** automatically when the client's payment email arrives.",
         "A second workflow: Gmail trigger on payment notifications → find the invoice → update the row.",
         "Gmail Trigger (`from:alerts@yourbank subject:credited`) → Code: regex the invoice number or amount from the email → Sheets **Append or Update** `{invoice_no, status: 'paid'}`. Reminders stop automatically, because paid rows are filtered out."),
    ],
    "Q07": [
        (1, "Add a **Recruiting** category for job applications.",
         "Categories are just name + description.",
         "Add `Recruiting`: *\"Job applications, CVs, candidate follow-ups\"*, create the Gmail label, and wire the new output. Put the most specific categories first."),
        (2, "Measure accuracy: log every classification and let yourself correct it.",
         "You can't improve what you don't measure.",
         "Append `{time, subject, predicted}` to a `Labels` sheet. Once a week, fill a `correct` column for 30 rows; accuracy = matches / 30. Improve the descriptions that confuse the model and re-measure."),
    ],
    "Q08": [
        (1, "Post only articles matching **keywords** (e.g. \"AI\", \"automation\").",
         "Filter before dedupe, so skipped items aren't remembered.",
         "Add a **Filter**: `{{ /\\b(ai|automation|n8n)\\b/i.test($json.title) }}` is true, placed before *Only New Links*."),
        (2, "Add an AI-written one-line hook per article.",
         "LLM chain per item, after the Limit (so you pay for max 5).",
         "After *Max 5 per Run*, add a Basic LLM Chain + Gemini: *\"Write one catchy line (max 15 words) about: {{ $json.title }}\"*. Use `{{ $json.text }}` in the Telegram message."),
    ],
    "P01": [
        (1, "Add **purchase order** matching: flag invoices without a known PO number.",
         "Extract a `po_number` attribute and look it up in a POs sheet.",
         "Add the attribute `po_number` to the extractor. After Validate, **Sheets → Get rows** from `POs` where `po_number` matches (alwaysOutputData on). IF nothing is found, send it to Exceptions with reason *\"unknown PO\"*. This is the start of a real **2-way match**."),
        (2, "Detect **duplicate invoices with different numbers** (same vendor, same amount, same week).",
         "Exact dedupe keys miss re-issued invoices. Add a fuzzy check.",
         "Before the ledger, read the Ledger rows for that vendor from the last 7 days and flag if any `total` equals this total. Route matches to approval with the reason *\"possible duplicate of INV-…\"* instead of blocking them, because humans decide ambiguous cases."),
    ],
    "P02": [
        (1, "Add the customer's **last order** to the AI context.",
         "Look it up by the sender's email before drafting.",
         "Between Triage and Draft Answer, add **Sheets → Get rows** from `Orders` where `email = sender` (alwaysOutputData). Include `{{ JSON.stringify($json) }}` in the prompt as *\"Customer context\"*. Answers become specific, not generic."),
        (2, "Measure the copilot: how often do agents send the draft **unchanged**?",
         "Compare the AI draft with what was actually sent.",
         "Store `{threadId, draft}` in a sheet when drafting. A daily workflow reads your **Sent** mail for those threads and computes the similarity (e.g. the share of identical sentences). Report the % sent unchanged, by FAQ entry. That tells you which answers to fix and when auto-send might be safe."),
    ],
    "P03": [
        (1, "Include a **runbook link** per alert name in the Slack message.",
         "A small lookup table in code.",
         "In *Decide Action*: `const RUNBOOKS = { HighErrorRate: 'https://wiki/runbooks/5xx', DiskFilling: 'https://wiki/runbooks/disk' };` and add `runbook: RUNBOOKS[a.labels?.alertname] || ''` to the output. Show it in Slack."),
        (2, "**Escalate** if nobody acknowledges a P1 within 10 minutes.",
         "Wait, then check an acknowledgement flag.",
         "After paging, add **Wait 10 min** → Jira *Get issue* → IF the status is still *Open* (nobody picked it up), page the secondary on-call and post *\"Escalated\"* in Slack. For a real ack button, use Slack **Send and Wait** as the page."),
    ],
    "P04": [
        (1, "Skip weekends: never send follow-ups on Saturday or Sunday.",
         "Use *Wait → At specified time* with a computed date.",
         "Replace *Wait 3 Days* with **Wait → At specified time**: `{{ (d => d.weekday > 5 ? d.plus({ days: 8 - d.weekday }) : d)($now.plus({ days: 3 }).set({ hour: 10, minute: 0 })) }}`. This moves Saturday or Sunday to Monday 10:00."),
        (2, "Personalise email 2 using the lead's **company website**.",
         "Fetch the homepage, extract text, let AI write one relevant sentence.",
         "Before Email 2: HTTP GET `https://{{ $('Lead Record').item.json.email.split('@')[1] }}` (On Error → Continue) → HTML extract `body` text → LLM chain: *\"One sentence connecting their business to automating {{ need }}\"*. Insert it into Email 2."),
    ],
    "P05": [
        (1, "Re-queue failed rows automatically once, before giving up.",
         "Track `attempts` in the sheet.",
         "In *Mark Error*, add `attempts = {{ (Number($('Loop in Batches of 10').item.json.attempts) || 0) + 1 }}` and change `status` to `{{ (Number($('Loop in Batches of 10').item.json.attempts) || 0) + 1 < 2 ? 'pending' : 'error' }}`. (A Set node can't read a field it's setting in the same step, so compute it again.) Add an `attempts` column to the sheet. The next run retries failed rows once."),
        (2, "Send a **Slack summary** only when the whole list is finished.",
         "Check whether any pending rows remain after the run.",
         "After *Summary*, **Sheets → Get rows** `status = pending` (alwaysOutputData) → IF none are left, post to Slack *\"Enrichment complete: X done, Y errors\"*. Schedule the workflow hourly until that fires."),
    ],
    "P06": [
        (1, "Make the finance threshold depend on the **cost centre**.",
         "Replace the single number with a lookup.",
         "In ⚙️ Config, store `thresholds = {\"Engineering\": 200000, \"Sales\": 50000, \"default\": 100000}` (type Object). IF: `{{ amount > ($('⚙️ Config').item.json.thresholds[cost_centre] ?? $('⚙️ Config').item.json.thresholds.default) }}`."),
        (2, "Add a **reason** field when someone rejects.",
         "Use a custom-form response in Send and Wait.",
         "Change the approvals to **Response type: Custom form** with a dropdown (Approve / Reject) and a textarea *Reason*. Route on the dropdown value, write `reason` to the audit row, and include it in the requester's email."),
    ],
    "P07": [
        (1, "Add a **Designer** checklist item: *\"Invite to design critique\"*.",
         "The checklist is data inside *Build Checklist*.",
         "Add `['Manager', 'Invite to design critique']` to `byRole.Designer`. No wiring changes: the Jira and aggregation steps adapt to any count."),
        (2, "Send a **day-30 check-in survey** to the new joiner.",
         "Long wait → form link.",
         "After *Summary to HR*, add **Wait → At specified time**: `{{ DateTime.fromISO($('New Joiner Form (HR)').first().json['Start date']).plus({ days: 30 }).set({ hour: 10 }) }}` → Gmail with a link to an n8n Form (*\"How's it going?\"*) that writes to a sheet."),
    ],
    "P08": [
        (1, "Sync the **priority** field to Jira too.",
         "Jira priorities are objects; map names to IDs.",
         "Add to Jira create/update: *Priority* = a lookup `{\"High\": \"2\", \"Medium\": \"3\", \"Low\": \"4\"}[$json.priority]` (check your Jira's priority IDs via *Get priorities*). The hash already includes priority, so changes trigger updates."),
        (2, "Pull the **Jira status** back into a read-only sheet column.",
         "One-way sync in the other direction, for one field.",
         "Add a second schedule: Sheets read rows with `jira_key` → Jira *Get issue* per row → Set `{row_id, jira_status}` → Sheets upsert by `row_id`. Don't include `jira_status` in the hash, or you'll create an update loop."),
    ],
    "P09": [
        (1, "Force **at least 4 distinct sources** before writing.",
         "Make it a rule in the system prompt and check it in code.",
         "Prompt: *\"Do not write the report until you've read at least 4 pages from different domains.\"* After the agent, add a Code node that counts unique domains in the Sources list; if fewer than 4, prepend a warning to the email."),
        (2, "Add a **critic** agent that reviews the report before it's sent.",
         "A second LLM that only checks claims against the cited sources.",
         "After the Research Agent, add a Basic LLM Chain: *\"List any sentence whose claim isn't supported by the cited URL text. Output JSON {issues: [...]}\"*. Append the issues to the email as \"⚠️ Reviewer notes\"."),
    ],
    "P10": [
        (1, "Add a **`list_open_tickets`** read-only tool.",
         "Any sub-workflow can become a tool.",
         "Create a sub-workflow: Execute Workflow Trigger (`email`) → Jira *Get many* (`reporter = email AND statusCategory != Done`) → Set a compact list. Add a **Call n8n Workflow** tool to P10 with a clear description."),
        (2, "Add a **write** tool (`create_ticket`) that requires human approval.",
         "Tools can pause for approval, like any workflow.",
         "Sub-workflow: inputs (summary, customer_email) → Slack **Send and Wait** to the support lead → IF approved → Jira create → return `{created: key}`; else return `{created: false, reason: 'declined'}`. The AI client gets an honest answer either way."),
    ],
    "P11": [
        (1, "Also redact **UPI IDs** (e.g. `name@okhdfcbank`).",
         "UPI looks like an email but with a bank handle and no dot TLD.",
         "Add the rule `['UPI', /\\b[\\w.-]{2,}@(ok\\w+|ybl|ibl|axl|paytm|upi)\\b/gi]` **before** the EMAIL rule, so it wins."),
        (2, "Add **per-user rate limiting** (max 20 requests/hour).",
         "Count per user in static data, reset hourly.",
         "In *Redact PII* (or a node before it): `const s = $getWorkflowStaticData('global'); const k = user + ':' + $now.toFormat('yyyyMMddHH'); s[k] = (s[k] || 0) + 1; if (s[k] > 20) → blocked`. Return **429** via Respond to Webhook."),
    ],
    "P12": [
        (1, "Add **support backlog** as a 4th KPI.",
         "Add a 4th branch and a 4th Merge input.",
         "Add Jira `project = SUP AND statusCategory != Done` (or your helpdesk API) → Aggregate → Merge input 4 (set *Number of inputs* to 4). Add `support_backlog` in Compute KPIs; the table and narrative pick it up automatically."),
        (2, "Keep **12 weeks** of KPIs and chart the trend.",
         "Static data isn't history. Store weekly rows.",
         "After Compute KPIs, append `{week: $today.startOf('week').toISODate(), ...kpis}` to a `KPIs` sheet. Read the last 12 rows for a line chart (QuickChart `line`). Trends show whether a change is a blip or a direction."),
    ],
})
